const nameEditPopupSelector = ".nameEditPopup",
  addPhotoPopupSelector = ".addPhotoPopup",
  avatarEditPopupSelector = ".avatarEditPopup",
  photoAddPopup = document.querySelector("#addPhotoPopup"),
  nameEditBtn = document.querySelector(".profile__name-edit-button"),
  photoAddBtn = document.querySelector(".profile__add-button"),
  nameEditForm = document.querySelector("#nameEditForm"),
  nameInput = nameEditForm.querySelector("#usernameInput"),
  jobInput = nameEditForm.querySelector("#userJobInput"),
  userName = document.querySelector(".profile__name"),
  userJob = document.querySelector(".profile__description"),
  photoForm = document.querySelector("#photoAddForm"),
  photoTitleInput = document.querySelector("#photoTitle"),
  linkInput = document.querySelector("#photoLink"),
  cardsContainer = document.querySelector(".elements__container"),
  imgPopupCaption = document.querySelector(".popup__image-name"),
  popupList = Array.from(document.querySelectorAll(".popup")),
  photoSubmitBtn = document.querySelector("#photoSubmitBtn"),
  avatar = document.querySelector(".profile__avatar-wrapper"),
  avatarEditOverlay = document.querySelector(".profile__avatar-overlay"),
  avatarEditPopup = document.querySelector("#avatarEditPopup"),
  avatarInput = document.querySelector("#avatarInput"),
  avatarEditForm = document.querySelector("#avatarEditForm"),
  avatarPic = document.querySelector(".profile__avatar");

const config = {
  formSelector: ".popup__form",
  inputSelector: ".popup__input",
  submitButtonSelector: ".popup__button",
  inactiveButtonClass: "popup__button_disabled",
  inputErrorClass: "popup__input_type_error",
  errorClass: "popup__input-error_active",
};

export {
  nameEditPopupSelector,
  addPhotoPopupSelector,
  avatarEditPopupSelector,
  photoAddPopup,
  nameEditBtn,
  photoAddBtn,
  nameEditForm,
  nameInput,
  jobInput,
  userName,
  userJob,
  photoForm,
  photoTitleInput,
  linkInput,
  cardsContainer,
  imgPopupCaption,
  popupList,
  photoSubmitBtn,
  avatar,
  avatarEditOverlay,
  avatarEditPopup,
  avatarInput,
  avatarEditForm,
  avatarPic,
  config,
};
